### ISSUE TITLE
Idea: reduce wasm file

### ISSUE THREAD

**Issue by longhan** [kovacsv/occt-import-js#20]
Hi kovacsv,

Can occt-import-js.wasm file fize reduce in case compile for each file type separate? i.e. step, iges, brep

If that could you please give me some guideline for archive that?

Thank you, LH

**Comment by kovacsv** [comment]
It can be reduced, but not a lot. The rest of the code is needed for all import formats, so you can save only 1-2 megabytes by removing a format. Probably the only exception is the brep, if you need brep only the file size can be lower since it needs less code. But even if you do that, I don't think you can go below 15-18 megabytes.

**Comment by longhan** [comment]
Thank you. If that is the case, there are not worth to take effort.
